### ISSUE TITLE
uncaught exception: spawn ffmpeg ENOENT

### ISSUE THREAD

**Issue by kopierschnitte** [schmupu/ioBroker.ring#27]
Hello!
Thanks for this great adapter. It works quite perfect but somehow, it refuses to save the stream whenever the doorbell generates an event.
Adapter version is 1.1.2. NodeJs v10.20.1 / NPM 6.14.4`

host.iobroker | 2020-05-05 06:42:40.104 | error | Caught by controller[3]: (node:14359) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js proc
-- | -- | -- | --
host.iobroker | 2020-05-05 06:42:40.104 | error | Caught by controller[2]: (node:14359) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by
host.iobroker | 2020-05-05 06:42:40.104 | error | Caught by controller[1]: at fulfilled (/opt/iobroker/node_modules/ring-client-api/lib/api/sip-session.js:5:58)
host.iobroker | 2020-05-05 06:42:40.104 | error | Caught by controller[1]: at Generator.next (<anonymous>)
host.iobroker | 2020-05-05 06:42:40.103 | error | Caught by controller[1]: at SipSession.<anonymous> (/opt/iobroker/node_modules/ring-client-api/lib/api/sip-session.js:141:22)
host.iobroker | 2020-05-05 06:42:40.103 | error | Caught by controller[1]: at Socket.Writable.write (_stream_writable.js:299:11)
host.iobroker | 2020-05-05 06:42:40.103 | error | Caught by controller[1]: at writeOrBuffer (_stream_writable.js:399:5)
host.iobroker | 2020-05-05 06:42:40.103 | error | Caught by controller[1]: at doWrite (_stream_writable.js:415:12)
host.iobroker | 2020-05-05 06:42:40.103 | error | Caught by controller[1]: at Socket._write (net.js:726:8)
host.iobroker | 2020-05-05 06:42:40.103 | error | Caught by controller[1]: at Socket._writeGeneric (net.js:714:5)
host.iobroker | 2020-05-05 06:42:40.103 | error | Caught by controller[1]: at writeGeneric (internal/stream_base_commons.js:73:3)
host.iobroker | 2020-05-05 06:42:40.103 | error | Caught by controller[1]: at afterWriteDispatched (internal/stream_base_commons.js:78:25)
host.iobroker | 2020-05-05 06:42:40.102 | error | Caught by controller[1]: (node:14359) UnhandledPromiseRejectionWarning: Error: write EPIPE
host.iobroker | 2020-05-05 06:42:40.102 | error | Caught by controller[0]: '/media/usb/ring/livestream24229631_1588653759082.mp4' ] }
host.iobroker | 2020-05-05 06:42:40.102 | error | Caught by controller[0]: '10',
host.iobroker | 2020-05-05 06:42:40.102 | error | Caught by controller[0]: '-t',
host.iobroker | 2020-05-05 06:42:40.102 | error | Caught by controller[0]: 'copy',
host.iobroker | 2020-05-05 06:42:40.102 | error | Caught by controller[0]: '-vcodec',
host.iobroker | 2020-05-05 06:42:40.102 | error | Caught by controller[0]: 'aac',
host.iobroker | 2020-05-05 06:42:40.101 | error | Caught by controller[0]: '-acodec',
host.iobroker | 2020-05-05 06:42:40.101 | error | Caught by controller[0]: 'pipe:',
host.iobroker | 2020-05-05 06:42:40.101 | error | Caught by controller[0]: '-i',
host.iobroker | 2020-05-05 06:42:40.101 | error | Caught by controller[0]: 'sdp',
host.iobroker | 2020-05-05 06:42:40.101 | error | Caught by controller[0]: '-f',
host.iobroker | 2020-05-05 06:42:40.101 | error | Caught by controller[0]: 'pipe,udp,rtp,file,crypto',
host.iobroker | 2020-05-05 06:42:40.101 | error | Caught by controller[0]: '-protocol_whitelist',
host.iobroker | 2020-05-05 06:42:40.101 | error | Caught by controller[0]: [ '-hide_banner',
host.iobroker | 2020-05-05 06:42:40.100 | error | Caught by controller[0]: spawnargs:
host.iobroker | 2020-05-05 06:42:40.100 | error | Caught by controller[0]: path: 'ffmpeg',
host.iobroker | 2020-05-05 06:42:40.100 | error | Caught by controller[0]: syscall: 'spawn ffmpeg',
host.iobroker | 2020-05-05 06:42:40.100 | error | Caught by controller[0]: code: 'ENOENT',
host.iobroker | 2020-05-05 06:42:40.100 | error | Caught by controller[0]: errno: 'ENOENT',
host.iobroker | 2020-05-05 06:42:40.100 | error | Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:63:19)
host.iobroker | 2020-05-05 06:42:40.099 | error | Caught by controller[0]: at onErrorNT (internal/child_process.js:415:16)
host.iobroker | 2020-05-05 06:42:40.099 | error | Caught by controller[0]: at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
host.iobroker | 2020-05-05 06:42:40.098 | error | Caught by controller[0]: { Error: spawn ffmpeg ENOENT
ring.0 | 2020-05-05 06:42:39.489 | info | (14359) Terminated (NO_ERROR): Without reason
ring.0 | 2020-05-05 06:42:39.488 | info | (14359) terminating
ring.0 | 2020-05-05 06:42:39.474 | info | (14359) Closing Adapter
ring.0 | 2020-05-05 06:42:39.473 | error | at process._tickCallback (internal/process/next_tick.js:63:19)
ring.0 | 2020-05-05 06:42:39.473 | error | at onErrorNT (internal/child_process.js:415:16)
ring.0 | 2020-05-05 06:42:39.473 | error | at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
ring.0 | 2020-05-05 06:42:39.473 | error | (14359) Error: spawn ffmpeg ENOENT
ring.0 | 2020-05-05 06:42:39.472 | error | (14359) uncaught exception: spawn ffmpeg ENOENT
ring.0 | 2020-05-05 06:42:39.270 | info | (14359) Sarting LiveStream for 10 sec.
ring.0 | 2020-05-05 06:42:39.270 | info | (14359) Making Livestream (0)
ring.0 | 2020-05-05 06:42:39.079 | info | (14359) Making snapshot
ring.0 | 2020-05-05 06:42:39.071 | info | (14359) Ding Dong for Id 24229631 (motion, ringing)

`

**Comment by kopierschnitte** [comment]
Sorry, my fault. FFMPEG isn't available (headless setup). So maybe it could be an enhancement to check the availability of FFMPEG ;-)
