### ISSUE TITLE
Frage Refreshtoken erstellen

### ISSUE THREAD

**Issue by Brookyman** [schmupu/ioBroker.ring#36]
Hallo ich verstehe nicht ganz wie ich den Refreshtoken erstellen kann. Wo muss ich das genau machen? Im Putty? In welchem Pfand??

Vielen Dank im voraus!

**Comment by schmupu** [comment]
Das steht in der README unter Install & Configuration wie du den Token installieren musst. Sonst auch einmal im Forum danach suchen. Da gibt es auch noch ein paar Tipps.

**Comment by schmupu** [comment]
Oder hier einmal schauen #21

**Comment by Brookyman** [comment]
da kommt bei mir folgender Fehler:

Error: Cannot find module '/opt/iobroker/node_modules/iobroker.ring/node_modules/ring-client-api/ring-auth-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by Brookyman** [comment]
habe:
node 10.19.0
npm 6.13.4
Admin 4.0.10

**Comment by schmupu** [comment]
Hast du auch hier auch geschaut? #19
Bitte erst alle Kombinationen versuchen und wenn es dann immer noch nicht funktioniert, bitte detailliert beschreiben was du alles versucht hast inkl. Fehlermeldungen. Dann sehen wir weiter.

**Comment by Brookyman** [comment]
Ja. Mit der Anleitung von Elzershark kommt folgenden meldung:

root@ioBroker-Tinker:~# npx -p ring-client-api ring-auth-cli
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/.npm/_npx/9700/lib/node_modules/ring-client-api/node_modules/ffmpeg-for-homebridge/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffmpeg-for-homebridge@0.0.6 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffmpeg-for-homebridge@0.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-14T07_14_34_377Z-debug.log
Install for ring-client-api@latest failed with code 1

**Comment by schmupu** [comment]
Versuche einmal folgendes:

```
npm install -g --unsafe-perm homebridge-camera-ffmpeg
npx -p ring-client-api ring-auth-cli
```

**Comment by schmupu** [comment]
Wenn das nicht geht, kannst Du vorher noch das Paket zu installieren: https://www.npmjs.com/package/ffmpeg-for-homebridge
Danach nochmals `npx -p ring-client-api ring-auth-cli` ausführen

**Comment by Brookyman** [comment]
Leider über beide wege auch keinen Erfolg. Ich weiss nicht ob es was zu tun hat, dass ich ein Tinkerboard mit Debian Stretch habe?

der Fehler bleibt der gleiche. Bei:

root@ioBroker-Tinker:~# npm i ffmpeg-for-homebridge

> ffmpeg-for-homebridge@0.0.6 install /root/node_modules/ffmpeg-for-homebridge
> node install.js

ffmpeg version 4.2.2-d1e8be3 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-indev=alsa --enable-outdev=alsa
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100

ffmpeg has been downloaded to /root/node_modules/ffmpeg-for-homebridge/ffmpeg
Thank you for using https://github.com/homebridge/ffmpeg-for-homebridge

npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

+ ffmpeg-for-homebridge@0.0.6
updated 1 package and audited 27 packages in 2.513s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by schmupu** [comment]
Such hier einmal nach der Lösung. Diese Library und Programme zum erstellen des Refreshtokens nutze ich in ioBroker um auf die Ring Geräte zuzugreifen. Ich würde jetzt auch nichts anderes tun, da der Fehler nichts mit ioBroker direkt zu tun.

**Comment by Matzeinmypocket** [comment]
cd /opt/iobroker/node_modules/iobroker.ring/node_modules/ring-client-api
node ring-auth-cli

Damit hats bei mir funktioniert. Ansonsten hatte ich die gleiche Fehlermeldung (ffmpeg). Nutze Synology mit Docker-Image.
